[package]
name = "send_message"
version = "1.0.0"
authors = []

[addresses]
DecentralizedMOOCs = '0xf270492be053cfc7ada6544121eae9d1196bc920e7eb84cff25125f21fc0b634'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]